#!/bin/ksh -x
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2013 Nexenta Systems, Inc.  All rights reserved.
#

# Load new ZFS binaries onto a test machine.

cpu=`uname -p`

# Where is ROOT? (arg 1? env? ../proto?)
if [ "$1" ] ; then
  ROOT=$1
elif [ "$ROOT" ] ; then
  :
elif [ -d ../proto ] ; then
  ROOT=`cd ..; pwd`/proto/root_$cpu
else
  echo "ROOT env?"
  exit 1
fi

# Where is destination?
if [ "$2" ] ; then
  DEST=$2
else
  echo "Can not run this on root!"
  exit 1
fi

case $cpu in
i386)
	ARCH64=amd64
	;;
sparc)
	ARCH64=sparcv9
	;;
*)  echo "Huh?" ; exit 1;;
esac

# Stop on error, and make noise
set -ex

# Stop the service
# XXXX

# Unload old smbfs
# XXX can't unload zfs...

# Copy in the new binaries
while read f
do
  if [ -f $ROOT/$f ] ; then
    if [ -f $DEST/$f.orig ] ; then
      rm -f $DEST/$f
    else
      mv $DEST/$f $DEST/$f.orig
    fi
    cp $ROOT/$f $DEST/$f
  else
    echo "$ROOT/$f not found!"
  fi
  # Compare the list below with
  # pkg/manifests/system-file-system-zfs.mf
done <<EOF
kernel/drv/${ARCH64}/zfs
kernel/drv/zfs
kernel/fs/${ARCH64}/zfs
kernel/fs/zfs
kernel/kmdb/${ARCH64}/zfs
kernel/kmdb/zfs
lib/libzfs.so.1
lib/libzfs_core.so.1
lib/llib-lzfs
lib/llib-lzfs.ln
lib/llib-lzfs_core
lib/llib-lzfs_core.ln
lib/${ARCH64}/libzfs.so.1
lib/${ARCH64}/libzfs_core.so.1
lib/${ARCH64}/llib-lzfs.ln
lib/${ARCH64}/llib-lzfs_core.ln
sbin/zfs
sbin/zpool
usr/lib/${ARCH64}/libzfs_jni.so.1
usr/lib/${ARCH64}/libzpool.so.1
usr/lib/fs/zfs/bootinstall
usr/lib/fs/zfs/fstyp.so.1
usr/lib/libzfs_jni.so.1
usr/lib/libzpool.so.1
usr/lib/mdb/kvm/${ARCH64}/zfs.so
usr/lib/mdb/kvm/zfs.so
usr/lib/mdb/proc/${ARCH64}/libzpool.so
usr/lib/mdb/proc/libzpool.so
usr/lib/sysevent/modules/zfs_mod.so group=sys
usr/lib/zfs/availdevs
usr/sbin/$(ARCH32)/zdb
usr/sbin/${ARCH64}/zdb
usr/sbin/zstreamdump
EOF

# XXX fixup hard links?
# hardlink path=kernel/fs/$(ARCH64)/zfs target=../../../kernel/drv/$(ARCH64)/zfs
# $(i386_ONLY)hardlink path=kernel/fs/zfs target=../../kernel/drv/zfs
# hardlink path=usr/lib/fs/zfs/fstyp target=../../../sbin/fstyp
# hardlink path=usr/sbin/zdb target=../../usr/lib/isaexec


bootadm update-archive -v -R $DEST

# chmod?
# modload?
# start svc?
