#!/bin/sh

# Upgrade path:
#
# divert some of the coreutils binaries so that we can
# install new ones
mkdir -p /usr/gnu/bin 2>/dev/null
coreutil_ver="`dpkg -s coreutils|awk '/^Version:/ {print $2}'`"
if test "x$coreutil_ver" != x; then
	if dpkg --compare-versions $coreutil_ver le 5.93-5nexenta5; then
		dpkg-divert --add --package sunwcsu --rename --divert /usr/gnu/bin/du /usr/bin/du
		dpkg-divert --add --package sunwcsu --rename --divert /usr/gnu/bin/df /usr/bin/df
	else
		if dpkg-divert --list | grep /usr/bin/du >/dev/null; then
			dpkg-divert --remove /usr/bin/du
		fi
		if dpkg-divert --list | grep /usr/bin/df >/dev/null; then
			dpkg-divert --remove /usr/bin/df
		fi
	fi
fi

exit 0
