#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright 2015 Nexenta Systems, Inc.  All rights reserved.
#

#
# And expect script to handle input of the Chapsecret since the input
# cannot be redirected due to getpasswd() library function being
# called by iscsiadm and itadm which will not take simple input redirection as
# input.
#

set force_conservative 1  ;# set to 1 to force conservative mode even if
                          ;# script wasn't run conservatively originally
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep .1
                exp_send -s -- $arg
        }
}

set timeout 5
set prompt "(%|#|\\$|%]) $"
set cmd [lindex $argv 0]
set secret [lindex $argv 1]
set RloginHost [lindex $argv 2]

eval spawn ssh $RloginHost -l root

expect -re $prompt
		
send -- "$cmd\r"
expect {
        "Enter secret:*" {
                send -- "$secret\r"
                exp_continue
        }
        "Re-enter secret:*" {
                send -- "$secret\r"
        }
}
expect -re $prompt
send -- "echo ret=\$?\r"
send -h "exit\r"
expect eof
exit
