#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Qlogic Communication Systems, Inc.
#

#
# NAME
#	swreset.exp
#
# DESCRIPTION
#	The Expect script will send commands to the Qlogic
#	switch to reset a switch. 
#

set force_conservative 1  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}


set timeout -1
set switch_ip [lindex ${argv} 0]
set switch_adm [lindex ${argv} 1]
set switch_pass [lindex ${argv} 2]
spawn telnet $switch_ip
expect {
  "Escape*" { exp_continue }
  " login: " {
      send -- "$switch_adm\r"
  exp_continue
  }
"Password: " {
    send -- "$switch_pass\r"
 }
}

send -- "date\r"
expect " #> ";
send -- "admin start\r"
expect " (admin) #> ";
send -- "reset\r"
send -- "y\r"
expect eof
