#! /bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
#pragma ident	"%Z%%M%	%I%	%E% SMI"
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
 
PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH


BASEDIR=${BASEDIR:-/}

# Select the correct add_drv options to execute.
# Only attempt to load the driver on a running system
if [ "$BASEDIR" = "/" ]; then
        ADD_DRV="add_drv"
else
        ADD_DRV="add_drv -b ${BASEDIR}"
fi

EXIT=0


not_installed() {
	driver=$1
	grep "^${driver} " ${BASEDIR}/etc/name_to_major > /dev/null 2>&1
	return $?
}

not_installed ipmi ||
${ADD_DRV} ipmi || 
EXIT=1

exit ${EXIT}
