#!/bin/sh
#
# Nexenta upgrade fixups

if [ -f /var/svc/manifest/network/pfil.xml ]; then
	svcadm disable svc:/network/pfil:default >/dev/null 2>&1
	svccfg delete svc:/network/pfil:default >/dev/null 2>&1
	rm -f /var/svc/manifest/network/pfil.xml
fi

exit 0
